development:
  adapter: mysql
  database: omgimg
  host: localhost
  username: root
  password: REPLACEME

production:
  adapter: mysql
  database: omgimg
  host: localhost
  username: root
  password: REPLACEME
